# © OpenShot Studios, LLC
#
# SPDX-License-Identifier: LGPL-3.0-or-later

name: findopenmp-test
on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: bash
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
      LDFLAGS: -L/opt/homebrew/opt/libomp/lib
      CPPFLAGS: -I/opt/homebrew/opt/libomp/include

    steps:
      - uses: actions/checkout@v4

      - name: Install macOS dependencies
        run: |
          brew install libomp

      - name: Clang reproducer
        if: matrix.compiler.cc == 'clang'
        run: |
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_MODULE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_BUILD_TYPE=Debug --debug-trycompile
          cmake --build build -- VERBOSE=1

      - name: GCC reproducer
        if: matrix.compiler.cc == 'gcc'
        run: |
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_BUILD_TYPE=Debug --debug-trycompile
          cmake --build build -- VERBOSE=1

      - name: Export failed build tree as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ matrix.compiler.cc }}
          path: 'build/'

  baseline:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: bash
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
      LDFLAGS: -L/opt/homebrew/opt/libomp/lib
      CPPFLAGS: -I/opt/homebrew/opt/libomp/include

    steps:
      - uses: actions/checkout@v4

      - name: Install macOS dependencies
        run: |
          brew install libomp

      - name: Clang package-less build
        if: matrix.compiler.cc == 'clang'
        run: |
          cmake -B build_nopackage -S . -G "Unix Makefiles" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_MODULE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_BUILD_TYPE=Debug -DUSE_PACKAGE=0 \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build_nopackage -- VERBOSE=1

      - name: Clang baseline build
        if: matrix.compiler.cc == 'clang'
        run: |
          cmake -B build_single -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_MODULE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_BUILD_TYPE=Debug
          cmake --build build_single -- VERBOSE=1

      - name: GCC package-less build
        if: matrix.compiler.cc == 'gcc'
        run: |
          cmake -B build_nopackage -S . -G "Unix Makefiles" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_BUILD_TYPE=Debug -DUSE_PACKAGE=0 \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build_nopackage -- VERBOSE=1

      - name: GCC baseline build
        if: matrix.compiler.cc == 'gcc'
        run: |
          cmake -B build_single -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_BUILD_TYPE=Debug 
          cmake --build build_single -- VERBOSE=1

