# © OpenShot Studios, LLC
#
# SPDX-License-Identifier: LGPL-3.0-or-later

name: findopenmp-test
on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
        config: [ 'single', 'multi' ]
    defaults:
      run:
        shell: bash
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - uses: actions/checkout@v2

      - name: Install macOS dependencies
        if: ${{ runner.os == 'macos' }}
        run: |
          brew install libomp

      - name: Build reproducer
        run: |
          export CMAKE_EXTRA="${CMAKE_EXTRA}
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"

          if [ "_${{ matrix.compiler.cc }}" == "_clang" ]; then
            export CMAKE_EXTRA="${CMAKE_EXTRA} \
            -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_MODULE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++";
          fi

          if [ "_${{ matrix.config }}" == "_multi" ]; then
            export CMAKE_EXTRA="${CMAKE_EXTRA} \
              -DCMAKE_OSX_ARCHITECTURES=\"x86_64;arm64\"";
          fi

          mkdir build
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_BUILD_TYPE="Debug" \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install" \
            ${CMAKE_EXTRA}

          cmake --build build -- VERBOSE=1
