# © OpenShot Studios, LLC
#
# SPDX-License-Identifier: LGPL-3.0-or-later

name: findopenmp-test
on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: bash
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - uses: actions/checkout@v2

      - name: Install macOS dependencies
        run: |
          brew install libomp

      - name: Clang reproducer
        if: matrix.compiler.cc == 'clang'
        run: |
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_MODULE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -- VERBOSE=1

      - name: GCC reproducer
        if: matrix.compiler.cc == 'gcc'
        run: |
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -- VERBOSE=1

      - name: Clang baseline build
        if: matrix.compiler.cc == 'clang'
        run: |
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_MODULE_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++ \
            -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -- VERBOSE=1
          
      - name: GCC baseline build
        if: matrix.compiler.cc == 'gcc'
        run: |
          cmake -B build -S . -G "Unix Makefiles" \
            --trace-source=FindOpenMP.cmake --trace-expand \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_BUILD_TYPE=Debug 
          cmake --build build -- VERBOSE=1

